"""Remove username column from users table

Revision ID: 21398fde6a54
Revises: 8f400118daca
Create Date: 2025-10-19 03:19:42.192727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21398fde6a54'
down_revision: Union[str, None] = '8f400118daca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_column('usuarios', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('username', sa.VARCHAR(), nullable=True))
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=1)
    # ### end Alembic commands ###
