# alembic/versions/<id>_reordenar_columna_marca_en_productos.py (MODIFICADO)

"""Reordenar columna marca en productos

Revision ID: <some_id>
Revises: <previous_id>
Create Date: ...

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3515e33788eb'
down_revision = 'b10d48747515'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('marca',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'N/A'"))

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('marca',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'N/A'"))

    # ### end Alembic commands ###
