"""Añadir columna marca a productos

Revision ID: 3bf8624900ef
Revises: 21398fde6a54
Create Date: 2025-10-19 22:46:07.246811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf8624900ef'
down_revision: Union[str, None] = '21398fde6a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('marca', sa.String(), nullable=False, server_default='N/A'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'marca')
    # ### end Alembic commands ###
