"""Agregar image_url a la tabla productos

Revision ID: 83af9d97115e
Revises: 0ef4e96a3551
Create Date: 2025-06-27 06:19:12.102975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83af9d97115e'
down_revision: Union[str, None] = '0ef4e96a3551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'image_url')
    # ### end Alembic commands ###
