"""Add name, lastname, birthdate to users table

Revision ID: 8f400118daca
Revises: f7ea7a03136c
Create Date: 2025-10-19 03:09:57.134055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f400118daca'
down_revision: Union[str, None] = 'f7ea7a03136c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(), nullable=False, server_default='N/A'))
        batch_op.add_column(sa.Column('apellido', sa.String(), nullable=False, server_default='N/A'))
        batch_op.add_column(sa.Column('fecha_nacimiento', sa.Date(), nullable=False, server_default='1900-01-01'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('fecha_nacimiento')
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')
    # ### end Alembic commands ###
